version: "3"
services:
  sc4sc: 
    image: sc4sc:prototype
    ports: 
      - "8000:8000"
    volumes:
      - ./https:/sc4sc/https
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      ELASTIC_URL: elasticsearch:9200
      ELASTIC_SYNONYM_PATH: searchData/synonym.txt
      ELASTIC_BUILDINGS_PATH: /sc4sc/searchData/buildings.txt
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgres://root:password@db:5432/database_production
      KEYFILE_PATH: /sc4sc/klaytn/rn/data/keystore/key
      PASSWORD_PATH: /sc4sc/klaytn/rn/data/keystore/password
      SECRET: 123123
      PRIVKEY: temp
    command: bash -c 'while !</dev/tcp/db/5432 || !</dev/tcp/redis/6379; do sleep 1; done; node /sc4sc/backend/server/app.js'
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : password
      POSTGRES_DB: database_production
