version: "3"
services:
  sc4sc: 
    image: sc4sc:prototype
    build: .
    ports: 
      - "12422:8000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      POSTGRES_URL: postgres://root:password@db:5432/database_production
      # Change two keys in production
      SECRET: 123123
      PRIVKEY: temp
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; node /backend/server/app.js'
  db:
    image: postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : password
      POSTGRES_DB: database_production
