version: "3"
services:
  sc4sc: 
    image: sc4sc:prototype
    ports: 
      - "8000:8000"
      - "443:443"
    volumes:
      - ./https:/sc4sc/https
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgres://root:password@db:5432/database_production
      KEYFILE_PATH: /sc4sc/klaytn/rn/data/keystore/key
      PASSWORD_PATH: /sc4sc/klaytn/rn/data/keystore/password
      ENABLE_HTTPS: 1
      HTTPS_KEY_PATH: /sc4sc/https/key.pem
      HTTPS_CERT_PATH: /sc4sc/https/cert.pem
    command: bash -c 'while !</dev/tcp/db/5432 || !</dev/tcp/redis/6379; do sleep 1; done; ./run_app_with_blockchain.sh'
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : password
      POSTGRES_DB: database_production